[book]
title = "CS6501, Fall 2026"
authors = ["Kevin Sullivan"]
language = "en"
description = "CS6501, Fall 2026"
src = "src"

[build]
build-dir = "book"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/kevinsullivan/Lean4CS1"
additional-css = ["issue-box.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.stamp]
command = "python3 scripts/stamp_commit.py"
renderer = ["html"]
